version: '3'
services:

  # todo upgrade to influxdb2
  influxdb:
    #image: influxdb:1.8-alpine
    image: mendhak/arm32v6-influxdb
    env_file: config/influxdb.env
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana:8.3.4
    depends_on:
      - influxdb
    env_file: config/grafana.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/

  php:
    build:
      context: ./php
    depends_on:
      - influxdb
    links:
      - influxdb
    env_file: config/php.env
    ports:
      - '8080:8080'
#      - '8443:443'
    volumes:
      - ./php/src/app:/var/www/html/app:rw,cached
      - ./php/src/public:/var/www/html/public:rw,cached
      - ./php/src/scripts:/var/www/html/scripts:rw,cached
      - ./php/src/sessions:/var/www/html/sessions:rw,cached
      - ./php/src/vendor:/var/www/html/vendor:r,cached

volumes:
  grafana_data: { }
  influxdb_data: { }
