# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: Redis
    orgId: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  # <string, required> name of the datasource. Required
- name: Redis
  # <string, required> datasource type. Required
  type: redis-datasource
  # <string, required> access mode. direct or proxy. Required
  access: proxy
  # <int> org id. will default to orgId 1 if not specified
  orgId: 1
  # <string> url
  url: redis://redis:6379
  version: 1
  jsonData:
    client: standalone
    poolSize: 5
    timeout: 10
    pingInterval: 0
    pipelineWindow: 0
  editable: false
