{
 "title": "SpotiSights - Spotify Insights",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "SHOW TAG VALUES WITH KEY = \"user\" "
   },
   {
    "name": "artist",
    "label": "Artist",
    "query": "SHOW TAG VALUES WITH KEY = \"artists\" "
   }
  ]
 },
 "panels": [
  { "title": "totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total songs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "most time listened to by artist",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "artists" ], "type": "tag" }
     ],
     "measurement": "track_history",
     "query": "SELECT sum(\"duration_ms\")  / 1000 AS \"duration\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/) AND $timeFilter GROUP BY \"artists\" ORDER BY time DESC SLIMIT 10",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  { "title": "summary by time period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "avg BPM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "tempo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg acousticness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "acousticness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg danceability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "danceability" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg energy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg instrumentalness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "instrumentalness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg liveness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "liveness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg speechiness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "speechiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg valence",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "valence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "avg valence",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "valence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "averages",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT mean(\"danceability\"), mean(\"energy\") FROM \"track_history\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "danceability" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg danceability" ], "type": "alias" }
      ],
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg energy" ], "type": "alias" }
      ],
      [
       { "params": [ "instrumentalness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg instrumentalness" ], "type": "alias" }
      ],
      [
       { "params": [ "acousticness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg acousticness" ], "type": "alias" }
      ],
      [
       { "params": [ "speechiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg speechiness" ], "type": "alias" }
      ],
      [
       { "params": [ "liveness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg liveness" ], "type": "alias" }
      ],
      [
       { "params": [ "valence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg valence" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "BPM by time",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "measurement": "track_history",
     "select": [
      [
       { "params": [ "tempo" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "history",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "measurement": "spotisights4",
     "query": "SELECT \"user\",\"artists\",\"song\",\"duration_ms\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"artists\" =~ /$artist/) AND $timeFilter ORDER BY time DESC",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" },
      { "condition": "AND", "key": "artists", "operator": "=~", "value": "/^$artist$/" }
     ]
    }
   ]
  }
 ]
}