{
 "title": "Current User",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "user",
    "label": "User",
    "query": "SHOW TAG VALUES WITH KEY = \"user\" WHERE \"user\" =~ /^${__user.login}$/ "
   },
   {
    "name": "service",
    "label": "Service",
    "query": "SHOW TAG VALUES WITH KEY = \"service\" WHERE \"user\" =~ /^${__user.login}$/  "
   },
   {
    "name": "artist",
    "label": "Artist",
    "query": "SELECT DISTINCT(\"artists\") FROM (SELECT \"artists\",\"duration_ms\" FROM \"track_history\" WHERE \"user\" =~ /^$user$/ AND $timeFilter)"
   }
  ]
 },
 "panels": [
  { "title": "totals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "total played tracks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT count(\"duration_ms\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/)",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "total duration listened",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT sum(\"duration_ms\") /1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/)",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "total duration listened by period",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "30m" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "track_history",
     "query": "SELECT sum(\"duration_ms\") / 1000 / 60 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter GROUP BY \"user\", time($interval) fill(0)",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "total played tracks by period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT count(\"duration_ms\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "total duration listened by period",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT sum(\"duration_ms\") /1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "/1000/60" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  { "title": "audio features by time period", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "median tempo",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"tempo\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "tempo" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median danceability",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"danceability\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "danceability" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median energy",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"energy\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median instrumentalness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"instrumentalness\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "instrumentalness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median acousticness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"acousticness\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "acousticness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median speechiness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"speechiness\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "speechiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median liveness",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"liveness\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "liveness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "median valence",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT median(\"valence\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "valence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "averages",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT mean(\"danceability\") AS \"avg danceability\", mean(\"energy\") AS \"avg energy\", mean(\"instrumentalness\") AS \"avg instrumentalness\", mean(\"acousticness\") AS \"avg acousticness\", mean(\"speechiness\") AS \"avg speechiness\", mean(\"liveness\") AS \"avg liveness\", mean(\"valence\") AS \"avg valence\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "danceability" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg danceability" ], "type": "alias" }
      ],
      [
       { "params": [ "energy" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg energy" ], "type": "alias" }
      ],
      [
       { "params": [ "instrumentalness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg instrumentalness" ], "type": "alias" }
      ],
      [
       { "params": [ "acousticness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg acousticness" ], "type": "alias" }
      ],
      [
       { "params": [ "speechiness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg speechiness" ], "type": "alias" }
      ],
      [
       { "params": [ "liveness" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg liveness" ], "type": "alias" }
      ],
      [
       { "params": [ "valence" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "avg valence" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "artists", "operator": "=~", "value": "/^$artist$/" }
     ]
    }
   ]
  },
  {
   "title": "tempo",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "tempo by time",
     "type": "heatmap",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "measurement": "track_history",
       "query": "SELECT \"tempo\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
       "select": [
        [
         { "params": [ "tempo" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "user", "operator": "=~", "value": "/^$user$/" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "daily statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "median tempo by time of day",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "morning (5-10 UTC)",
     "query": "SELECT median(\"tempo\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^([5-9]|1[0])$/)"
    },
    {
     "alias": "noon (10-14 UTC)",
     "query": "SELECT median(\"tempo\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(1[0-3])$/)"
    },
    {
     "alias": "afternoon (14-17 UTC)",
     "query": "SELECT median(\"tempo\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(1[4-6])$/) "
    },
    {
     "alias": "evening (17-21 UTC)",
     "query": "SELECT median(\"tempo\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(1[7-9]|2[0])$/) "
    },
    {
     "alias": "night (21-05 UTC)",
     "query": "SELECT median(\"tempo\") FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(2[1-4]|[0-4])$/) "
    }
   ]
  },
  {
   "title": "duration by time of day",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "morning (5-10 UTC)",
     "query": "SELECT sum(\"duration_ms\") / 1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^([5-9])$/)"
    },
    {
     "alias": "noon (10-14 UTC)",
     "query": "SELECT sum(\"duration_ms\") / 1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(1[0-3])$/)"
    },
    {
     "alias": "afternoon (14-17 UTC)",
     "query": "SELECT sum(\"duration_ms\") / 1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(1[4-6])$/) "
    },
    {
     "alias": "evening (17-21 UTC)",
     "query": "SELECT sum(\"duration_ms\") / 1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(1[7-9]|2[0])$/) "
    },
    {
     "alias": "night (21-05 UTC)",
     "query": "SELECT sum(\"duration_ms\") / 1000 FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter AND \"hour_of_day\" =~ /^(2[1-4]|[0-4])$/) "
    }
   ]
  },
  {
   "title": "duration by day",
   "type": "table",
   "gridPos": { "h": 7, "w": 5, "x": 11, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "track_history",
     "query": "SELECT sum(\"duration_ms\") / 1000 AS \"duration\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter GROUP BY time(1d) fill(0)",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "top genre by day",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "track_history",
     "query": "\nSELECT \"genre\", top(\"value_sum\",1) as \"tracks\" from (\nSELECT sum(\"value\") AS \"value_sum\", min(\"genre\") FROM \"genre_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter) GROUP BY \"genre\"\n) GROUP BY time($__interval)",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  { "title": "genres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "top 10 artist genres",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "query": "\nSELECT top(\"value_sum\", 10) as \"tracks\", \"genre\" from (\nSELECT sum(\"value\") AS \"value_sum\" FROM \"genre_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter) GROUP BY \"genre\"\n)"
    }
   ]
  },
  {
   "title": "artist genres",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 9, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "genre_history",
     "query": "SELECT sum(\"value\") FROM \"genre_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/ AND $timeFilter) GROUP BY \"genre\", time($interval) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  { "title": "artists", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "listened time by artist",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "artists" ], "type": "tag" }
     ],
     "measurement": "track_history",
     "query": "SELECT sum(\"duration_ms\") / 1000 AS \"duration\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter GROUP BY \"artists\"",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "top 10 artists by listened time",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 9, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT top(\"minutes\", 10) / 1000 / 60 as \"duration\", \"artists\" from (\nSELECT sum(\"duration_ms\") AS \"minutes\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter GROUP BY \"artists\"\n)",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [
         3
        ],
        "type": "top"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" }
     ]
    }
   ]
  },
  {
   "title": "most playbacks by tracks",
   "type": "table",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "artists" ], "type": "tag" }
     ],
     "measurement": "track_history",
     "query": "SELECT \"duration_ms\",\"track\",\"artists\" FROM \"track_history\" WHERE \"track\" != '' AND ( \"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "duration" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" },
      { "condition": "AND", "key": "artists", "operator": "!=", "value": "select tag value" }
     ]
    }
   ]
  },
  { "title": "general", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "history",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "track_history",
     "query": "SELECT \"service\",\"artists\",\"track\",\"duration_ms\" / 1000 as \"duration\" FROM \"track_history\" WHERE (\"user\" =~ /^$user$/ AND \"service\" =~ /^$service$/ AND \"artists\" =~ /$artist/) AND $timeFilter ORDER BY time DESC LIMIT 1000",
     "select": [
      [
       { "params": [ "duration_ms" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "user", "operator": "=~", "value": "/^$user$/" },
      { "condition": "AND", "key": "artists", "operator": "=~", "value": "/^$artist$/" }
     ]
    }
   ]
  }
 ]
}